//
// Created by imwood04 on 1/19/2024.
//

#ifndef CPPTUTORIAL_GETMODULEBASEADDRESS_H
#define CPPTUTORIAL_GETMODULEBASEADDRESS_H


class getModuleBaseAddress {

};


#endif //CPPTUTORIAL_GETMODULEBASEADDRESS_H
